name: NetFramework.Legacy.CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    if: "!contains(toJSON(github.event.commits.*.message), '[skip-ci]')"

    env:
      Solution_Name: CelesteTAS-EverestInterop.sln

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1

      - name: Build with MSBuild
        run: msbuild $env:Solution_Name -t:build -restore -p:Configuration=Release -m
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: CelesteTAS
          path: CelesteTAS-EverestInterop/bin/net452