name: NetFramework.Legacy.CI.Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: windows-2022

    env:
      Solution_Name: CelesteTAS-EverestInterop.sln

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1

      - name: Build with MSBuild
        run: msbuild $env:Solution_Name -t:build -restore -p:Configuration=Release,RestoreLockedMode=true -m

      - name: Zip Files
        uses: papeloto/action-zip@v1
        with:
          files: CelesteTAS-EverestInterop/bin/net452/
          dest: CelesteTAS_${{github.ref_name}}.zip

      - name: Tagged Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: CelesteTAS_${{github.ref_name}}.zip